name: Publsih

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: github.repository_owner == 'bitpatty'
    name: Publish extension
    runs-on: ubuntu-latest
    environment: visual-studio-marketplace
    env:
      VSCE_PAT: ${{ secrets.VISUALSTUDIO_PUBLISHER_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
      - run: npm install
      - run: npm run build
      - run: npm run package
      - run: npm run publish
